name: llm-for-se
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - langgraph
      - langchain
      - typing_extensions
      - radon
      - ollama
      - black
      - ruff
